
export interface PaymentRecord {
  id: string;
  rowNumber: number;
  paymentDate: string; // ISO format
  interestRate: number;
  principalBalance: number;
  principalPaid: number;
  interestPaid: number;
  taxesPaid: number;
  insurancePaid: number;
  totalPayment: number;
  checkNumber: string;
  isAutoGenerated?: boolean;
}

export interface SummaryStats {
  totalPrincipalPaid: number;
  totalInterestPaid: number;
  totalTaxesPaid: number;
  totalInsurancePaid: number;
  remainingBalance: number;
  paymentCount: number;
}
